DROP TABLE IF EXISTS Surveys;
DROP TABLE IF EXISTS Exams;
DROP TABLE IF EXISTS Meeting;
DROP TABLE IF EXISTS Students;
DROP TABLE IF EXISTS Class;
DROP TABLE IF EXISTS Course;
DROP TABLE IF EXISTS Teachers;
DROP TABLE IF EXISTS Classroom;






